version: '3.9'

services:
  ingress:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  ui:
    container_name: ui
    build: ./src/ui
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=pbid.localhost

  api:
    container_name: api
    build: ./src/api
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=api.pbid.localhost
      - PORT=5000